name: Compilar Entities
on:
  push:
    branches:
      - "main"
      - "test"
      - "dev"
jobs:
  build:
    runs-on: 'ubuntu-latest'
    env:
      solution: Database
      version: 1.0.${{ github.run_number }}
      versionSuffix: ${{ github.ref_name }}
    steps:
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}